apiVersion: v1
kind: Service
metadata:
    name: ms-service
spec:
    selector:
        app: ms-service
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081
    type: LoadBalancer